/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package elektrikprojesi;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author intiz
 */
public class AdminEkrani extends javax.swing.JDialog {

    DefaultTableModel model1;
    DefaultTableModel model2;
    AdminIslemler adminIslemler = new AdminIslemler();

   
    
    /**
     * Creates new form AdminEkrani
     */
    public AdminEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model1 = (DefaultTableModel) bireyselMusteriTablosu.getModel();
        bireyselMusteriGoruntule();
        model2 = (DefaultTableModel) kurumsalMusteriTablosu.getModel();
        kurumsalMusteriGoruntule();
    }
    public void kurumsalMusteriGoruntule(){
        
        model2.setRowCount(0);
        
        ArrayList<KurumsalMusteri> kurumsalmusteriler = new ArrayList<KurumsalMusteri>();
        
        kurumsalmusteriler = adminIslemler.kurumsalMusterileriGetir();
        
        if (kurumsalmusteriler != null){
            
            for(KurumsalMusteri kurumsalMusteri: kurumsalmusteriler){
                Object[] eklenecek = {kurumsalMusteri.getId(),kurumsalMusteri.getOdenecekTutar()};
                model2.addRow(eklenecek);
            
            }
        
        }
        
    }
    
   
    
    public void bireyselMusteriGoruntule(){
        
        model1.setRowCount(0);
        
        ArrayList<BireyselMusteri> bireyselmusteriler = new ArrayList<BireyselMusteri>();
        
        bireyselmusteriler = adminIslemler.bireyselMusterileriGetir();
        
        if (bireyselmusteriler != null){
            
            for(BireyselMusteri bireyselMusteri: bireyselmusteriler){
                Object[] eklenecek = {bireyselMusteri.getId(),bireyselMusteri.getOdenecekTutar()};
                model1.addRow(eklenecek);
            
            }
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kurumsalAramaCubugu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bireyselMusteriTablosu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        kurumsalMusteriTablosu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bireyselAramaCubugu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        odenecekTutarAlani1 = new javax.swing.JTextField();
        bireyselGuncelle = new javax.swing.JButton();
        mesajYazisi = new javax.swing.JLabel();
        odenecekTutarAlani2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kurumsalGuncelle = new javax.swing.JButton();
        bireyselSil = new javax.swing.JButton();
        kurumsalSil = new javax.swing.JButton();
        bireyselEkle = new javax.swing.JButton();
        kurumsalEkle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 100, 0, 0));

        jLabel1.setText("Kurumsal Ara:");

        kurumsalAramaCubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kurumsalAramaCubuguKeyReleased(evt);
            }
        });

        bireyselMusteriTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ödenecek Tutar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bireyselMusteriTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bireyselMusteriTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bireyselMusteriTablosu);
        if (bireyselMusteriTablosu.getColumnModel().getColumnCount() > 0) {
            bireyselMusteriTablosu.getColumnModel().getColumn(0).setResizable(false);
            bireyselMusteriTablosu.getColumnModel().getColumn(1).setResizable(false);
        }

        kurumsalMusteriTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Ödenecek Tutar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kurumsalMusteriTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kurumsalMusteriTablosuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(kurumsalMusteriTablosu);
        if (kurumsalMusteriTablosu.getColumnModel().getColumnCount() > 0) {
            kurumsalMusteriTablosu.getColumnModel().getColumn(0).setResizable(false);
            kurumsalMusteriTablosu.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel2.setText("Bireysel Ara:");

        bireyselAramaCubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bireyselAramaCubuguKeyReleased(evt);
            }
        });

        jLabel5.setText("Tutar:");

        bireyselGuncelle.setText("Veri Güncelle");
        bireyselGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bireyselGuncelleActionPerformed(evt);
            }
        });

        mesajYazisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mesajYazisi.setForeground(new java.awt.Color(255, 0, 51));

        jLabel7.setText("Tutar:");

        kurumsalGuncelle.setText("Veri Güncelle");
        kurumsalGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurumsalGuncelleActionPerformed(evt);
            }
        });

        bireyselSil.setText("Veri Sil");
        bireyselSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bireyselSilActionPerformed(evt);
            }
        });

        kurumsalSil.setText("Veri Sil");
        kurumsalSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurumsalSilActionPerformed(evt);
            }
        });

        bireyselEkle.setText("Veri Ekle");
        bireyselEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bireyselEkleActionPerformed(evt);
            }
        });

        kurumsalEkle.setText("Veri Ekle");
        kurumsalEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurumsalEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bireyselAramaCubugu)
                                        .addGap(87, 87, 87))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(odenecekTutarAlani1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bireyselGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bireyselSil, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bireyselEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kurumsalAramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(kurumsalEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kurumsalSil, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kurumsalGuncelle))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(odenecekTutarAlani2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kurumsalAramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(bireyselAramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odenecekTutarAlani2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(odenecekTutarAlani1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kurumsalEkle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesajYazisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(kurumsalGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kurumsalSil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bireyselGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bireyselSil, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bireyselEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void bireyselDinamikAra(String bireyselAra){
        
        TableRowSorter<DefaultTableModel> tr1 = new TableRowSorter<DefaultTableModel>(model1);
        
        bireyselMusteriTablosu.setRowSorter(tr1);

        
        
        tr1.setRowFilter(RowFilter.regexFilter(bireyselAra));

    }
    
    public void kurumsalDinamikAra(String bireyselAra){
        

        TableRowSorter<DefaultTableModel> tr2 = new TableRowSorter<DefaultTableModel>(model2);

        kurumsalMusteriTablosu.setRowSorter(tr2);
        
        

        tr2.setRowFilter(RowFilter.regexFilter(bireyselAra));
    }
    
    private void kurumsalAramaCubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kurumsalAramaCubuguKeyReleased
        String kurumsalAra = kurumsalAramaCubugu.getText();
        
        kurumsalDinamikAra(kurumsalAra);
    }//GEN-LAST:event_kurumsalAramaCubuguKeyReleased

    private void bireyselAramaCubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bireyselAramaCubuguKeyReleased
        String bireyselAra = bireyselAramaCubugu.getText();
        
        bireyselDinamikAra(bireyselAra);
    }//GEN-LAST:event_bireyselAramaCubuguKeyReleased

    private void bireyselGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bireyselGuncelleActionPerformed
        
        String odenecekTutar = odenecekTutarAlani1.getText();
        
        int selectedrow =  bireyselMusteriTablosu.getSelectedRow();
        
        if(selectedrow == -1){
            if (model1.getRowCount() == 0){
                mesajYazisi.setForeground(Color.red);
                mesajYazisi.setText("Tablo şu anda boş.");
            }
            else{
                mesajYazisi.setForeground(Color.red);
                mesajYazisi.setText("Lütfen değiştirilecek fatura seçin.");
            }
        }else{
            mesajYazisi.setText("");
            int id = (int)model1.getValueAt(selectedrow, 0);
            
            
            adminIslemler.bireyselGuncelle(id,odenecekTutar);
            
            bireyselMusteriGoruntule();
            mesajYazisi.setForeground(Color.green);
            mesajYazisi.setText("Veri güncellendi...");
            
            
        }
    }//GEN-LAST:event_bireyselGuncelleActionPerformed

    private void bireyselMusteriTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bireyselMusteriTablosuMouseClicked
        int selectedrow = bireyselMusteriTablosu.getSelectedRow();
        
        
        
        odenecekTutarAlani1.setText(model1.getValueAt(selectedrow, 1).toString());
    }//GEN-LAST:event_bireyselMusteriTablosuMouseClicked

    private void kurumsalMusteriTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kurumsalMusteriTablosuMouseClicked
        int selectedrow = kurumsalMusteriTablosu.getSelectedRow();
        
        odenecekTutarAlani2.setText(model2.getValueAt(selectedrow, 1).toString());
    }//GEN-LAST:event_kurumsalMusteriTablosuMouseClicked

    private void kurumsalGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurumsalGuncelleActionPerformed
        
        String odenecekTutar = odenecekTutarAlani2.getText();
        
        int selectedrow =  kurumsalMusteriTablosu.getSelectedRow();
        
        if(selectedrow == -1){
            if (model2.getRowCount() == 0){
                mesajYazisi.setForeground(Color.red);
                mesajYazisi.setText("Tablo şu anda boş.");
            }
            else{
                mesajYazisi.setForeground(Color.red);
                mesajYazisi.setText("Lütfen değiştirilecek fatura seçin.");
            }
        }else{
            mesajYazisi.setText("");
            int id = (int)model2.getValueAt(selectedrow, 0);
            
            
            adminIslemler.kurumsalGuncelle(id,odenecekTutar);
            
            kurumsalMusteriGoruntule();
            mesajYazisi.setForeground(Color.green);
            mesajYazisi.setText("Veri güncellendi...");
            
            
        }
    }//GEN-LAST:event_kurumsalGuncelleActionPerformed

    private void kurumsalSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurumsalSilActionPerformed
        mesajYazisi.setText("");
        
        int selectedrow =  kurumsalMusteriTablosu.getSelectedRow();
        
        if(selectedrow == -1){
            if (model2.getRowCount() == 0){
                mesajYazisi.setForeground(Color.red);
                mesajYazisi.setText("Tablo şu anda boş.");
            }
            else{
                mesajYazisi.setForeground(Color.red);
                mesajYazisi.setText("Lütfen silinecek veri seçin.");
            }
        }else{
            mesajYazisi.setText("");
            int id = (int)model2.getValueAt(selectedrow, 0);
            
            
            adminIslemler.kurumsalSil(id);
            
            kurumsalMusteriGoruntule();
            mesajYazisi.setText("Veri silindi...");
        }
    }//GEN-LAST:event_kurumsalSilActionPerformed

    private void bireyselSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bireyselSilActionPerformed
        mesajYazisi.setText("");
        
        int selectedrow =  bireyselMusteriTablosu.getSelectedRow();
        
        if(selectedrow == -1){
            if (model1.getRowCount() == 0){
                mesajYazisi.setForeground(Color.red);
                mesajYazisi.setText("Tablo şu anda boş.");
            }
            else{
                mesajYazisi.setForeground(Color.red);
                mesajYazisi.setText("Lütfen silinecek veri seçin.");
            }
        }else{
            mesajYazisi.setText("");
            int id = (int)model1.getValueAt(selectedrow, 0);
            
            
            adminIslemler.bireyselSil(id);
            
            bireyselMusteriGoruntule();
            mesajYazisi.setText("Veri silindi...");
        }
    }//GEN-LAST:event_bireyselSilActionPerformed


    private void bireyselEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bireyselEkleActionPerformed
        mesajYazisi.setText("");
        

        String odenecekTutar = odenecekTutarAlani1.getText();
        
        adminIslemler.bireyselEkle(odenecekTutar);
        bireyselMusteriGoruntule();
        mesajYazisi.setForeground(Color.green);
        mesajYazisi.setText("Veri eklendi...");
        mesajYazisi.setForeground(Color.red);
    }//GEN-LAST:event_bireyselEkleActionPerformed

    private void kurumsalEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurumsalEkleActionPerformed
        mesajYazisi.setText("");
        

        String odenecekTutar = odenecekTutarAlani2.getText();
        
        adminIslemler.kurumsalEkle(odenecekTutar);
       kurumsalMusteriGoruntule();
       
        mesajYazisi.setForeground(Color.green);
        mesajYazisi.setText("Veri eklendi...");
        mesajYazisi.setForeground(Color.red);
    }//GEN-LAST:event_kurumsalEkleActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminEkrani dialog = new AdminEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bireyselAramaCubugu;
    private javax.swing.JButton bireyselEkle;
    private javax.swing.JButton bireyselGuncelle;
    private javax.swing.JTable bireyselMusteriTablosu;
    private javax.swing.JButton bireyselSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kurumsalAramaCubugu;
    private javax.swing.JButton kurumsalEkle;
    private javax.swing.JButton kurumsalGuncelle;
    private javax.swing.JTable kurumsalMusteriTablosu;
    private javax.swing.JButton kurumsalSil;
    private javax.swing.JLabel mesajYazisi;
    private javax.swing.JTextField odenecekTutarAlani1;
    private javax.swing.JTextField odenecekTutarAlani2;
    // End of variables declaration//GEN-END:variables
}
