/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package elektrikprojesi;


import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author intiz
 */
public class BireyselMusteriEkrani extends javax.swing.JDialog {
    
    DefaultTableModel model;
    BireyseLIslemler bireyseLIslemler = new BireyseLIslemler();
    
    

    /**
     * Creates new form BireyselMusteriEkrani
     */
    public BireyselMusteriEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        model = (DefaultTableModel) bireyselMusteriTablosu.getModel();
        musteriGoruntule();
        
    }
    
    public void musteriGoruntule(){
        
        model.setRowCount(0);
        
        ArrayList<BireyselMusteri> bireyselmusteriler = new ArrayList<BireyselMusteri>();
        
        bireyselmusteriler = bireyseLIslemler.bireyselMusterileriGetir();
        
        if (bireyselmusteriler != null){
            
            for(BireyselMusteri bireyselMusteri: bireyselmusteriler){
                Object[] eklenecek = {bireyselMusteri.getId(),bireyselMusteri.getOdenecekTutar()};
                model.addRow(eklenecek);
            
            }
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bireyselMusteriTablosu = new javax.swing.JTable();
        aramaCubugu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        odeme = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        odenecekTutarAlani = new javax.swing.JTextField();
        mesajYazisi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kalanTutarAlani = new javax.swing.JTextField();
        girilenTutarAlani = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        geri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));

        bireyselMusteriTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Ödenecek Tutar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bireyselMusteriTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bireyselMusteriTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bireyselMusteriTablosu);
        if (bireyselMusteriTablosu.getColumnModel().getColumnCount() > 0) {
            bireyselMusteriTablosu.getColumnModel().getColumn(0).setResizable(false);
            bireyselMusteriTablosu.getColumnModel().getColumn(1).setResizable(false);
        }

        aramaCubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aramaCubuguKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Ara:");

        odeme.setText("Borç Öde");
        odeme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odemeActionPerformed(evt);
            }
        });

        jLabel5.setText("Ödenecek Tutar:");

        odenecekTutarAlani.setEditable(false);

        mesajYazisi.setForeground(new java.awt.Color(255, 0, 51));

        jLabel6.setText("Kalan Tutar:");

        kalanTutarAlani.setEditable(false);
        kalanTutarAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalanTutarAlaniActionPerformed(evt);
            }
        });

        girilenTutarAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girilenTutarAlaniActionPerformed(evt);
            }
        });

        jLabel7.setText("Ödemek istediğiniz Tutar:");

        geri.setText("Geri");
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(geri)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mesajYazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(odenecekTutarAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(girilenTutarAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(aramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(odeme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(kalanTutarAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(41, 41, 41)
                .addComponent(odeme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odenecekTutarAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(kalanTutarAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(girilenTutarAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addComponent(mesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(geri)
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        bireyselMusteriTablosu.setRowSorter(tr);
        
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void aramaCubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aramaCubuguKeyReleased
        String ara = aramaCubugu.getText();
        
        dinamikAra(ara);
    }//GEN-LAST:event_aramaCubuguKeyReleased

    private void bireyselMusteriTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bireyselMusteriTablosuMouseClicked
        int selectedrow = bireyselMusteriTablosu.getSelectedRow();
        kalanTutarAlani.setText("");
        
        odenecekTutarAlani.setText(model.getValueAt(selectedrow, 1).toString());
                
    }//GEN-LAST:event_bireyselMusteriTablosuMouseClicked

    private void odemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odemeActionPerformed
        
        int selectedrow = bireyselMusteriTablosu.getSelectedRow();
        double kalanTutar = 0;
        
        String odenecekTutar = model.getValueAt(selectedrow, 1).toString();
        
        String eskiTutar = odenecekTutarAlani.getText();
        String girTutar = girilenTutarAlani.getText();
        
        
         if (Double.parseDouble(girTutar) < Double.parseDouble(odenecekTutar)){
        
             kalanTutar  = Double.parseDouble(eskiTutar) - Double.parseDouble(girTutar);
            
             kalanTutarAlani.setText(String.valueOf(kalanTutar));
        
             mesajYazisi.setText("Ödenecek " + kalanTutar + " TL borcunuz kaldı...");
    
        }else if (Double.parseDouble(girTutar) == Double.parseDouble(odenecekTutar)){
        
            kalanTutar  = Double.parseDouble(eskiTutar) - Double.parseDouble(girTutar);
            
             kalanTutarAlani.setText(String.valueOf(kalanTutar));
        
             mesajYazisi.setText("Bu tarihe ait ödenecek borcunuz kalmadı...");
        }else if(Double.parseDouble(girTutar) > Double.parseDouble(eskiTutar)){
           
            mesajYazisi.setText("Lütfen borcunuzdan daha yüksek bir tutar girmeyiniz...");
        }
         
        
        
        if(selectedrow == -1){
            if (model.getRowCount() == 0){
                
                mesajYazisi.setText("Tablo şu anda boş.");
            }
            else{
                mesajYazisi.setText("Lütfen ödenecek fatura seçin.");
            }
        }else{
            int id = (int)model.getValueAt(selectedrow, 0);
            
            
            bireyseLIslemler.faturaOde(id,kalanTutar);
            
            musteriGoruntule();
            
            
        }
        
    }//GEN-LAST:event_odemeActionPerformed

    private void kalanTutarAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kalanTutarAlaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kalanTutarAlaniActionPerformed

    private void girilenTutarAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girilenTutarAlaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_girilenTutarAlaniActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
        BireyselElektrikHesaplamaEkrani bireyselElektrikHesaplamaEkrani = new BireyselElektrikHesaplamaEkrani();
        setVisible(false);
        
        bireyselElektrikHesaplamaEkrani.setVisible(true);
    }//GEN-LAST:event_geriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BireyselMusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BireyselMusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BireyselMusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BireyselMusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BireyselMusteriEkrani dialog = new BireyselMusteriEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aramaCubugu;
    private javax.swing.JTable bireyselMusteriTablosu;
    private javax.swing.JButton geri;
    private javax.swing.JTextField girilenTutarAlani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kalanTutarAlani;
    private javax.swing.JLabel mesajYazisi;
    private javax.swing.JButton odeme;
    private javax.swing.JTextField odenecekTutarAlani;
    // End of variables declaration//GEN-END:variables
}
