/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package elektrikprojesi;

import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author intiz
 */
public class KurumsalMusteriEkrani extends javax.swing.JDialog {
    
    DefaultTableModel model;
    KurumsaLIslemler kurumsaLIslemler = new KurumsaLIslemler();

    /**
     * Creates new form ElektrikEkrani
     * @param parent
     * @param modal
     */
    public KurumsalMusteriEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        model = (DefaultTableModel) kurumsalMusteriTablosu.getModel();
        musteriGoruntule();
    }
    public void musteriGoruntule(){
        
        model.setRowCount(0);
        
        ArrayList<KurumsalMusteri> kurumsalmusteriler = new ArrayList<KurumsalMusteri>();
        
        kurumsalmusteriler = kurumsaLIslemler.kurumsalMusterileriGetir();
        
        if (kurumsalmusteriler != null){
            
            for(KurumsalMusteri kurumsalMusteri: kurumsalmusteriler){
                Object[] eklenecek = {kurumsalMusteri.getId(),kurumsalMusteri.getOdenecekTutar()};
                model.addRow(eklenecek);
            
            }
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        kurumsalMusteriTablosu = new javax.swing.JTable();
        aramaCubugu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        odenecekTutarAlani = new javax.swing.JTextField();
        odeme = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        girilenTutarAlani = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kalanTutarAlani = new javax.swing.JTextField();
        mesajYazisi = new javax.swing.JLabel();
        geri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));

        kurumsalMusteriTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Ödenecek Tutar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kurumsalMusteriTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kurumsalMusteriTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kurumsalMusteriTablosu);
        if (kurumsalMusteriTablosu.getColumnModel().getColumnCount() > 0) {
            kurumsalMusteriTablosu.getColumnModel().getColumn(0).setResizable(false);
            kurumsalMusteriTablosu.getColumnModel().getColumn(1).setResizable(false);
        }

        aramaCubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aramaCubuguKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Ara:");

        jLabel5.setText("Ödenecek Tutar:");

        odenecekTutarAlani.setEditable(false);

        odeme.setText("Borç Öde");
        odeme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odemeActionPerformed(evt);
            }
        });

        jLabel4.setText("Ödemek İstediğiniz Tutar:");

        girilenTutarAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girilenTutarAlaniActionPerformed(evt);
            }
        });

        jLabel6.setText("Kalan Tutar:");

        kalanTutarAlani.setEditable(false);

        mesajYazisi.setForeground(new java.awt.Color(255, 0, 51));

        geri.setText("Geri");
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(odenecekTutarAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(girilenTutarAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kalanTutarAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(geri)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mesajYazisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(odeme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(odeme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odenecekTutarAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(girilenTutarAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(kalanTutarAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(geri)
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        kurumsalMusteriTablosu.setRowSorter(tr);
        
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void aramaCubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aramaCubuguKeyReleased
        String ara = aramaCubugu.getText();
        
        dinamikAra(ara);
    }//GEN-LAST:event_aramaCubuguKeyReleased

    private void odemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odemeActionPerformed
        int selectedrow = kurumsalMusteriTablosu.getSelectedRow();
        double kalanTutar = 0;
        
        String odenecekTutar = model.getValueAt(selectedrow, 1).toString();
        
        String eskiTutar = odenecekTutarAlani.getText();
        String girTutar = girilenTutarAlani.getText();

        
         if (Double.parseDouble(girTutar) < Double.parseDouble(odenecekTutar)){
        
             kalanTutar  = Double.parseDouble(eskiTutar) - Double.parseDouble(girTutar);
            
             kalanTutarAlani.setText(String.valueOf(kalanTutar));
        
             mesajYazisi.setText("Ödenecek " + kalanTutar + " TL borcunuz kaldı...");
    
        }else if (Double.parseDouble(girTutar) == Double.parseDouble(odenecekTutar)){
        
            kalanTutar  = Double.parseDouble(eskiTutar) - Double.parseDouble(girTutar);
            
             kalanTutarAlani.setText(String.valueOf(kalanTutar));
        
             mesajYazisi.setText("Bu tarihe ait ödenecek borcunuz kalmadı...");
        }else if(Double.parseDouble(girTutar) > Double.parseDouble(eskiTutar)){
           
            mesajYazisi.setText("Lütfen borcunuzdan daha yüksek bir tutar girmeyiniz...");
        }
         
        
        
        if(selectedrow == -1){
            if (model.getRowCount() == 0){
                
                mesajYazisi.setText("Tablo şu anda boş.");
            }
            else{
                mesajYazisi.setText("Lütfen ödenecek fatura seçin.");
            }
        }else{
            int id = (int)model.getValueAt(selectedrow, 0);
            
            
            kurumsaLIslemler.faturaOde(id,kalanTutar);
            
            musteriGoruntule();
            
            
        }
       
        
    }//GEN-LAST:event_odemeActionPerformed

    private void kurumsalMusteriTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kurumsalMusteriTablosuMouseClicked
        int selectedrow = kurumsalMusteriTablosu.getSelectedRow();
        kalanTutarAlani.setText("");
        

        odenecekTutarAlani.setText(model.getValueAt(selectedrow, 1).toString());
    }//GEN-LAST:event_kurumsalMusteriTablosuMouseClicked

    private void girilenTutarAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girilenTutarAlaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_girilenTutarAlaniActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
        KurumsalElektrikHesaplamaEkrani kurumsalElektrikHesaplamaEkrani = new KurumsalElektrikHesaplamaEkrani();
        setVisible(false);
        
        kurumsalElektrikHesaplamaEkrani.setVisible(true);
    }//GEN-LAST:event_geriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KurumsalMusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KurumsalMusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KurumsalMusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KurumsalMusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KurumsalMusteriEkrani dialog = new KurumsalMusteriEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aramaCubugu;
    private javax.swing.JButton geri;
    private javax.swing.JTextField girilenTutarAlani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kalanTutarAlani;
    private javax.swing.JTable kurumsalMusteriTablosu;
    private javax.swing.JLabel mesajYazisi;
    private javax.swing.JButton odeme;
    private javax.swing.JTextField odenecekTutarAlani;
    // End of variables declaration//GEN-END:variables
}
